services:
  vpn-proxy:
    build: .
    container_name: vpn-proxy
    env_file:
      - .env
    expose:
      - "3128"   # HTTP proxy
      - "1080"   # SOCKS5 proxy
    network_mode: host
    volumes:
      - ${PWD}/conf/xray.json:/etc/xray/conf.json:ro
    restart: unless-stopped
